name: Build & Push Docker image (Koyeb)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE: ${{ github.repository_owner }}/cdek-nginx-php
      TAG: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Optional: Docker Hub
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USER }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # .github/workflows/docker-publish.yml (фрагмент)
      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/nginx-php/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/cdek-nginx-php:latest
            ghcr.io/${{ github.repository_owner }}/cdek-nginx-php:${{ github.sha }}
          build-args: |
            SERVICE_CORE_URL=${{ secrets.SERVICE_CORE_URL }}
      
